# Generated by Django 5.2.2 on 2025-06-23 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_grado_alumno_curso_nota_padre_salon_alumno_salon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='profesores',
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='api.salon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='api.salon'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nota',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='api.alumno'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='api.curso'),
        ),
        migrations.AlterField(
            model_name='padre',
            name='alumnos',
            field=models.ManyToManyField(related_name='padres', to='api.alumno'),
        ),
        migrations.AlterField(
            model_name='padre',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'padre'}, on_delete=django.db.models.deletion.CASCADE, related_name='padre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salon',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salones', to='api.grado'),
        ),
    ]
