# Generated by Django 5.2.2 on 2025-06-23 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_curso_grado_remove_curso_profesores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salon'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'role': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curso',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salon'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alumno'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.curso'),
        ),
        migrations.AlterField(
            model_name='padre',
            name='alumnos',
            field=models.ManyToManyField(to='api.alumno'),
        ),
        migrations.AlterField(
            model_name='padre',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'padre'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salon',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grado'),
        ),
    ]
