# Generated by Django 5.2.2 on 2025-06-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_alumno_salon_alter_alumno_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='salon',
        ),
        migrations.AddField(
            model_name='curso',
            name='salones',
            field=models.ManyToManyField(to='api.salon'),
        ),
    ]
